### ISSUE TITLE
[add] 첫 펀째 페이지 상단 컴포넌트 구현

### ISSUE THREAD

**Issue by ingong** [SOPT28-Client-Design-folin/Folin-Web#6]
## 💡 Issue
첫 번째 페이지 상단 .

## 📝 todo
- [ ] 글꼴 적용 문제 해결
- [ ] 슬라이더 구현
- [ ] 베스트 스토리 컴포넌트 구현
- [ ] 키워드 컴포넌트 구현
- [ ] 슬라이더 반응형 구현
